from time import sleep
from tkinter import *
def Output(SolarArrayNumber,CGSTAmount,NonTaxAmount,Amount,FAmount,NonTaxAmount2,Tax2,FullTaxAmount,Subsidy):
    root=Tk()
    root.title("Final Billing Estimation")
    x=StringVar()
    y=StringVar()
    z=StringVar()
    w=StringVar()
    v=StringVar()
    u=StringVar()
    t=StringVar()
    r=StringVar()
    q=StringVar()
    x.set(CGSTAmount)
    z.set(Amount)
    w.set(FAmount)
    y.set(SolarArrayNumber)
    v.set(NonTaxAmount)
    u.set(NonTaxAmount2)
    t.set(Tax2)
    r.set(FullTaxAmount)
    q.set(int(Subsidy))
    print(SolarArrayNumber)
    print(y.get())
    S=Label(root,borderwidth=1,relief="solid",width=10,height=2,text=y.get(),bg='white')
    S.grid(row=1,column=2)
    A18=Label(root,borderwidth=1,relief='solid',width=15,height=2,text=x.get(),bg='white')
    A18.grid(row=1,column=4)
    A19=Label(root,borderwidth=1,relief='solid',width=15,height=2,text=x.get(),bg='white')
    A19.grid(row=1,column=5)
    A20=Label(root,borderwidth=1,relief='solid',width=20,height=4,text=v.get(),bg='white')
    A20.grid(row=1,column=3,rowspan=2)
    A21=Label(root,borderwidth=1,relief='solid',width=20,height=4,text=z.get(),bg='white')
    A21.grid(row=1,column=6,rowspan=2)
    A=Label(root,text="SL",borderwidth=1,relief="solid",width=10,height=4,bg='orange').grid(row=0,column=0)
    B=Label(root,text="Qty",borderwidth=1,relief="solid",width=10,height=4,bg='orange').grid(row=0,column=2)
    C=Label(root,text="Description",borderwidth=1,relief="solid",width=31,height=4,bg='orange').grid(row=0,column=1)
    D=Label(root,text="Taxable Value",borderwidth=1,relief="solid",width=20,height=4,bg='orange').grid(row=0,column=3)
    E=Label(root,text="CGST",borderwidth=1,relief="solid",width=15,height=4,bg='orange').grid(row=0,column=4)
    F=Label(root,text="SGST",borderwidth=1,relief="solid",width=15,height=4,bg='orange').grid(row=0,column=5)
    G=Label(root,text="Total Amount",borderwidth=1,relief="solid",width=20,height=4,bg='orange').grid(row=0,column=6)
    H=Label(root,text="Supply of Rooftop Solar\nPV System",borderwidth=1,relief="solid",width=31,height=4,bg='white').grid(row=1,column=1,rowspan=2)
    I=Label(root,text="1",borderwidth=1,relief="solid",width=10,height=4,bg='white').grid(row=1,column=0,rowspan=2)
    J=Label(root,text="2",borderwidth=1,relief="solid",width=10,height=4,bg='white').grid(row=3,column=0,rowspan=2)
    K=Label(root,text="3",borderwidth=1,relief="solid",width=10,height=4,bg='white').grid(row=5,column=0,rowspan=2)
    L=Label(root,text="TSSPDCL Application \nCharges",borderwidth=1,relief="solid",width=31,height=4,bg='white').grid(row=3,column=1,rowspan=2)
    M=Label(root,text="TSREDCO Application \nCharges",borderwidth=1,relief="solid",width=31,height=4,bg='white').grid(row=5,column=1,rowspan=2)
    N=Label(root,text="1",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=3,column=2)
    O=Label(root,text="1",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=5,column=2)
    P=Label(root,text="No's",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=4,column=2)
    Q=Label(root,text="No's",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=6,column=2)
    R=Label(root,text="kWp",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=2,column=2)
    T=Label(root,text="Rs.2500.00",borderwidth=1,relief="solid",width=20,height=4,bg='white').grid(row=3,column=3,rowspan=2)
    U=Label(root,text="Rs.3000.00",borderwidth=1,relief="solid",width=20,height=4,bg='white').grid(row=5,column=3,rowspan=2)
    V=Label(root,text="Rs.225.00",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=3,column=4)
    W=Label(root,text="Rs.270.00",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=5,column=4)
    X=Label(root,text="9%",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=4,column=4)
    Y=Label(root,text="9%",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=6,column=4)
    Z=Label(root,text="Rs.225.00",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=3,column=5)
    A1=Label(root,text="Rs.270.00",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=5,column=5)
    A2=Label(root,text="9%",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=4,column=5)
    A3=Label(root,text="9%",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=6,column=5)
    A4=Label(root,text="Rs.2,950.00",borderwidth=1,relief="solid",width=20,height=4,bg='white').grid(row=3,column=6,rowspan=2)
    A5=Label(root,text="Rs.3,540.00",borderwidth=1,relief="solid",width=20,height=4,bg='white').grid(row=5,column=6,rowspan=2)
    A6=Label(root,text="4",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=7,column=0)
    A7=Label(root,text="5",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=8,column=0)
    A8=Label(root,text="6",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=9,column=0)
    A9=Label(root,text="7",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=10,column=0)
    A10=Label(root,text="8",borderwidth=1,relief="solid",width=10,height=2,bg='white').grid(row=11,column=0)
    A11=Label(root,text="Total Cost Of System",borderwidth=1,relief="solid",width=62,height=2,bg='white').grid(row=7,column=1,columnspan=3)
    A12=Label(root,text="Total Tax Value",borderwidth=1,relief="solid",width=62,height=2,bg='white').grid(row=8,column=1,columnspan=3)
    A13=Label(root,text="Net Payable Amount (Billing Amount)",borderwidth=1,relief="solid",width=62,height=2,bg='white').grid(row=9,column=1,columnspan=3)
    A14=Label(root,text="MNRE contribution (Subsidy)",borderwidth=1,relief="solid",width=62,height=2,bg='white').grid(row=10,column=1,columnspan=3)
    A15=Label(root,text="Customer Contribution",borderwidth=1,relief="solid",width=62,height=2,bg='white').grid(row=11,column=1,columnspan=3)
    A16=Label(root,text="2.5%",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=2,column=4)
    A17=Label(root,text="2.5%",borderwidth=1,relief="solid",width=15,height=2,bg='white').grid(row=2,column=5)
    A22=Label(root,text="Rs."+u.get(),borderwidth=1,relief="solid",height=2,width=51,bg='white')
    A22.grid(row=7,column=4,columnspan=3)
    A23=Label(root,text="Rs."+t.get(),borderwidth=1,relief="solid",height=2,width=51,bg='white')
    A23.grid(row=8,column=4,columnspan=3)
    A24=Label(root,text="Rs."+r.get(),borderwidth=1,relief="solid",height=2,width=51,bg='white')
    A24.grid(row=9,column=4,columnspan=3)
    A25=Label(root,text="Rs."+q.get(),borderwidth=1,relief="solid",height=2,width=51,bg='white')
    A25.grid(row=10,column=4,columnspan=3)
    A26=Label(root,text="Rs."+w.get(),borderwidth=1,relief="solid",height=2,width=51,bg='white')
    A26.grid(row=11,column=4,columnspan=3)
    
